import React from "react";
import { Card } from "react-bootstrap";
import { Link} from "react-router-dom"
import { db, auth } from "../firebase";
import shortid from 'shortid';
import {getLab} from './CreateRoom';


class getUserLabRooms extends React.Component {
	constructor(props) {
    super(props);
    this.state = {
      labArray: "",
    };
  }

  async componentDidMount(){
    const userId = auth.currentUser.uid;
    const fetchPromises = [];

    if (userId){
      // console.log("getting labroom List for user: " + userId);
      const userDoc = await db.doc(`users/${userId}`).get(); //gets the users entire collection using their id in firestore
      const userData = userDoc.data();

      const labs = userData.labs; //gets the users lab list from their firestore collection
      if (labs){ //if labs exist
        labs.forEach((labId:String) => {  //for each lab in the users lablist
          const nextProm = db.doc(`labs/${labId}`).get(); //get the lab fields for that particular lab from the labs collection in firestore
          fetchPromises.push(nextProm); // and store the lab info into fetchpromises
        });

        const labsToDisplay = await Promise.all(fetchPromises);
        const labArray  = labsToDisplay.map((lab) => {return lab.data()}); //creates a new array which is populated with the result of lab.data()
        
        this.setState({ labArray});  
      }
    }
  }

  render(){ 
    const array = this.state.labArray;
    return (
      <div id ="row" className="lab-row">
        {
          // below Array.from() is used with an arrow function to manipulate the items in labArray - so for each item in the array, display a card and the lab name on the users dashboard.
          Array.from(array, child =>{ 
            const a = child.Lab_Name;
            return(
              //each lab card is associated with a specific key, this key is generated by shortid
              <Card id="lab-card-style-2" key={shortid.generate()}>
                <Link to='/create-room' onClick={() => getLab(a)} className = 'lab-links' style={{textDecoration: "none"}}>
                  <Card.Body>
                    {/* display the lab card and its name(.Lab_Name taken from the lab collection in firestore) on the dashboard */}
                      <h2 className="dash-cards-h2">{child.Lab_Name}</h2>   
                  </Card.Body>
                </Link>
              </Card>  
            )
          })
        }
      </div>

    )
  }
}

export default getUserLabRooms;
